# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_LCDNumberModeTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(362, 244)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 341, 191))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lcnBin = QtWidgets.QLCDNumber(self.widget)
        self.lcnBin.setObjectName("lcnBin")
        self.horizontalLayout_2.addWidget(self.lcnBin)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lcnOct = QtWidgets.QLCDNumber(self.widget)
        self.lcnOct.setObjectName("lcnOct")
        self.horizontalLayout_3.addWidget(self.lcnOct)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.lcnDec = QtWidgets.QLCDNumber(self.widget)
        self.lcnDec.setObjectName("lcnDec")
        self.horizontalLayout_4.addWidget(self.lcnDec)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lcnHex = QtWidgets.QLCDNumber(self.widget)
        self.lcnHex.setObjectName("lcnHex")
        self.horizontalLayout_5.addWidget(self.lcnHex)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 362, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        from PyQt5.QtGui import QRegExpValidator, QIntValidator
        from PyQt5.QtCore import QRegExp
        reg = QRegExp('^[0-9]*$')
        regExpValidator = QRegExpValidator(None)
        regExpValidator.setRegExp(reg)
        self.lineEdit.setValidator(regExpValidator)

        self.lcnDec.setDigitCount(10)
        self.lcnDec.display('AAA')

        self.lineEdit.editingFinished.connect(self.getValue)

    def getValue(self):
        lcdNumber = self.lineEdit.text()
        from PyQt5.QtWidgets import QLCDNumber
        self.lcnBin.setDigitCount(20)
        self.lcnBin.setMode(QLCDNumber.Bin)
        self.lcnBin.setProperty('value', lcdNumber)
        self.lcnOct.setDigitCount(20)
        self.lcnOct.setProperty('value', lcdNumber)
        self.lcnOct.setMode(QLCDNumber.Oct)
        self.lcnDec.setDigitCount(20)
        self.lcnDec.setProperty('value', lcdNumber)
        self.lcnDec.setMode(QLCDNumber.Dec)
        self.lcnHex.setDigitCount(20)
        self.lcnHex.setProperty('value', lcdNumber)
        self.lcnHex.setMode(QLCDNumber.Hex)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "请输入非负整数"))
        self.label_2.setText(_translate("MainWindow", "Bin：二进制"))
        self.label_3.setText(_translate("MainWindow", "Oct：八进制"))
        self.label_4.setText(_translate("MainWindow", "Dec：十进制"))
        self.label_5.setText(_translate("MainWindow", "Hex：十六进制"))


if __name__ == '__main__':
    import sys

    app = QtWidgets.QApplication(sys.argv)
    app.setStyle('Fusion')
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    app.exit(app.exec_())