# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_leditTest.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(495, 239)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 471, 179))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditInt = QtWidgets.QLineEdit(self.widget)
        self.lineEditInt.setObjectName("lineEditInt")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditInt)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditDouble = QtWidgets.QLineEdit(self.widget)
        self.lineEditDouble.setObjectName("lineEditDouble")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditDouble)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditRegExp = QtWidgets.QLineEdit(self.widget)
        self.lineEditRegExp.setObjectName("lineEditRegExp")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditRegExp)
        self.dataMaskLiedt = QtWidgets.QLineEdit(self.widget)
        self.dataMaskLiedt.setObjectName("dataMaskLiedt")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dataMaskLiedt)
        self.timeMaskLiedt = QtWidgets.QLineEdit(self.widget)
        self.timeMaskLiedt.setObjectName("timeMaskLiedt")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.timeMaskLiedt)
        self.SenMaskLiedt = QtWidgets.QLineEdit(self.widget)
        self.SenMaskLiedt.setObjectName("SenMaskLiedt")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.SenMaskLiedt)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.verticalLayout.addLayout(self.formLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 495, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "整数"))
        self.label_2.setText(_translate("MainWindow", "小数"))
        self.label_3.setText(_translate("MainWindow", "Email地址"))
        self.label_4.setText(_translate("MainWindow", "日期掩码"))
        self.label_5.setText(_translate("MainWindow", "时间掩码"))
        self.label_6.setText(_translate("MainWindow", "序列号掩码"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
